# .bashrc

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Command aliases.
alias puppet-lint='puppet-lint --no-class_inherits_from_params_class-check --no-variable_scope-check --no-80chars-check --no-class_parameter_defaults-check'
alias pl='puppet-lint'

# Path aliases.
alias bi='cd ~/puppet-construction/puppet-baseinfra/puppet-baseinfra/etc/puppet/modules'
alias dev='cd /etc/puppet/modules/dev/manifests'
alias dms='cd ~/puppet-dmsat1/puppet-dmsat1'
alias dns='cd /etc/puppet/modules/dns/manifests'
alias hier='cd /var/lib/hiera'
alias hosts='cd /var/lib/hiera/depzones/dmsat1/hosts'
alias ipt='cd ~/puppet-construction/puppet-construction/etc/puppet/modules/iptables/manifests'
alias lb='cd ~/puppet-construction/puppet-construction/etc/puppet/modules/lvs/manifests'
alias ldap='cd /etc/puppet/modules/ldap/manifests'
alias mod='cd /etc/puppet/modules'
alias nodes='cd /var/lib/hiera/depzones/dmsat1/hosts/'
alias ntp='cd /etc/puppet/modules/ntp/manifests'
alias pcs='cd ~/puppet-construction'
alias pcf='cd ~/puppet-configuration'
alias pin='cd ~/puppet-integration'
alias prof='cd /etc/puppet/modules/profiles/manifests'
alias prov='cd /etc/puppet/modules/prov/manifests'
alias pso='cd ~/puppet-software'
alias pst='cd ~/puppet-structure'
alias pto='cd ~/puppet-tools'
alias role='cd /etc/puppet/modules/roles/manifests'
alias sup='cd ~/puppet-construction/puppet-construction/etc/puppet/modules/support6/manifests'
alias tst='cd ~/puppet-construction/puppet-construction/etc/puppet/modules/test/manifests'
